name: Deploy to AWS S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master
    paths-ignore:
      - infra/*
      - .github/workflows/infra-deploy.yml
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    env:
      AWS_REGION: eu-central-1
      GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NodeJs Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.node_version }}

      - name: Dependency Installation
        run: npm install

      - name: App Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get workflow run-id
        id: infra
        run: |
          RUN_ID=$(gh run list -w "Create Infrastructure (S3 + CloudFront)" \
                               -s success -L 1 --json databaseId |
                   jq -r '.[0].databaseId')
          echo "run-id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          run-id: ${{ steps.infra.outputs.run-id }}
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          path: .

      - name: Read Data from tf_outputs.json
        id: tf
        run: |
          BUCKET=$(jq -r '.bucket_name.value' tf_outputs.json)
          DIST_ID=$(jq -r '.distribution_id.value' tf_outputs.json)
          echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
          echo "distribution_id=$DIST_ID" >> $GITHUB_OUTPUT

      - name: Upload to AWS S3
        run: aws s3 sync dist/ s3://${{ steps.tf.outputs.bucket }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ steps.tf.outputs.distribution_id }}" \
            --paths "/*"
