name: infra-deploy.yml
on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/deploy/s3_bucket/**'
      - '.github/workflows/infra-deploy.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init, Apply and Save Output
        run: |
          cd infra/deploy/s3_bucket
          terraform init
          terraform plan
          terraform apply -auto-approve
          terraform output -json > tf_outputs.json

      - name: Upload tf_outputs.json as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: infra/deploy/s3_bucket/tf_outputs.json

