name: Create Infrastructure (S3 + CloudFront)

on:
  workflow_run:
    workflows: ["Create CloudFront OAI"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Download OAI Artifact
        uses: actions/download-artifact@v4
        with:
          name: oai-terraform-outputs
          path: oai_output

      - name: Extract OAI ID
        id: extract_oai
        run: |
          OAI_ID=$(jq -r '.cloudfront_oai_id.value' oai_output/tf_outputs.json)
          echo "cloudfront_oai_id=$OAI_ID" >> $GITHUB_OUTPUT

      - name: Terraform Apply (S3)
        run: |
          cd infra/deploy/s3_bucket
          terraform init
          terraform apply -auto-approve \
            -var="cloudfront_oai_id=${{ steps.extract_oai.outputs.cloudfront_oai_id }}"
          terraform output -json > ../../tmp/s3_outputs.json

      - name: Terraform Apply (CloudFront)
        run: |
          cd infra/deploy/cloudfront
          terraform init
          terraform apply -auto-approve \
            -var="s3_bucket_domain_name=$(jq -r '.bucket_domain_name.value' ../../tmp/s3_outputs.json)" \
            -var="cloudfront_oai_id=${{ steps.extract_oai.outputs.cloudfront_oai_id }}"
          terraform output -json > ../../tmp/cloudfront_outputs.json

      - name: Merge Outputs
        run: |
          mkdir -p merged
          jq -s '.[0] * .[1]' tmp/s3_outputs.json tmp/cloudfront_outputs.json > merged/tf_outputs.json

      - name: Upload tf_outputs.json
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: merged/tf_outputs.json
